"""Trust boundary — strict models that validate external input BEFORE any domain logic branches on it.

Three kinds of external input cross this boundary:

  * the certificate text, which arrives from the extraction stub and is untrusted by construction —
    a supplier wrote it, and some of them are wrong;
  * the *derived* reference data (SPEC-7 acceptance table, supplier master), generated by
    `tools/derive_reference.py`;
  * the *hand-authored* policy (`reference/policy.json`) — the provisional rulings. Trusted in the
    sense that a person wrote and reviewed it, and validated anyway, because a malformed policy that
    silently drops a rule is the worst failure this system has.

`extra="forbid"` on every model: an unexpected key is an error, not a silent drop. A field the
reference data grew that this code does not know about must stop the run, not be ignored.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class RawExtraction(BaseModel):
    """What the extraction stage hands over. Text only — this system does no OCR (out of scope)."""

    model_config = ConfigDict(extra="forbid")

    doc_id: str = Field(min_length=1)
    text: str
    extractor: str = Field(min_length=1, description="which extractor produced this, for provenance")


class RawSpecAttribute(BaseModel):
    """One row of the SPEC-7 §2 acceptance table, as reviewed reference data."""

    model_config = ConfigDict(extra="forbid")

    attribute: str = Field(min_length=1)
    lower: float
    upper: float
    unit: str = Field(min_length=1)
    reportable_method: str = Field(min_length=1)


class RawSpec(BaseModel):
    """The acceptance specification. Carries its revision: a certificate citing a withdrawn
    revision is referred to Quality (SPEC-7 §4), so the revision is load-bearing, not a label."""

    model_config = ConfigDict(extra="forbid")

    document: str = Field(min_length=1)
    revision: str = Field(min_length=1)
    effective: str = Field(min_length=1)
    attributes: list[RawSpecAttribute] = Field(min_length=1)


class RawSupplierMaster(BaseModel):
    """The approved-supplier list. The ERP will not create a lot for a supplier not on it."""

    model_config = ConfigDict(extra="forbid")

    source: str = Field(min_length=1)
    suppliers: list[str] = Field(min_length=1)


# --- policy (hand-authored rulings) -------------------------------------------------------------
# Every model below allows the documentation keys the file carries (`ruling`, `owner`, `why`, …).
# They are not decoration: a ruling with no owner is one nobody can overturn, and the reason a rule
# exists is the thing a reviewer needs most. They are validated as present-and-typed, not ignored.


class RawUnitConversion(BaseModel):
    model_config = ConfigDict(extra="forbid")

    attribute: str = Field(min_length=1)
    from_unit: str = Field(min_length=1)
    to_unit: str = Field(min_length=1)
    factor: float = Field(gt=0)
    why: str = Field(min_length=1)


class RawSynonyms(BaseModel):
    model_config = ConfigDict(extra="forbid")

    ruling: str
    owner: str
    why: str
    map: dict[str, list[str]] = Field(min_length=1)


class RawDateConvention(BaseModel):
    model_config = ConfigDict(extra="forbid")

    supplier: str = Field(min_length=1)
    order: str = Field(pattern="^(DMY|MDY)$")
    evidence: list[str] = Field(min_length=1)
    resolves: list[str] = Field(default_factory=list)


class RawNotInferred(BaseModel):
    model_config = ConfigDict(extra="forbid")

    supplier: str
    why: str
    affects: list[str] = Field(default_factory=list)


class RawDateConventions(BaseModel):
    model_config = ConfigDict(extra="forbid")

    ruling: str
    owner: str
    why: str
    min_unambiguous_samples: int = Field(ge=1)
    conventions: list[RawDateConvention]
    explicitly_not_inferred: list[RawNotInferred] = Field(default_factory=list)


class RawRule(BaseModel):
    """One rule. `order` decides which finding leads, and therefore which queue the lot lands in."""

    model_config = ConfigDict(extra="forbid")

    id: str = Field(min_length=1)
    ruling: str = Field(min_length=1)
    order: int
    action: str = Field(pattern="^(accept|hold)$")
    route: str = Field(pattern="^(quality|procurement|supplier_query|intake_keying)$")
    message: str = Field(min_length=1)
    owner: str = Field(min_length=1)


class RawStaleness(BaseModel):
    model_config = ConfigDict(extra="forbid")

    ruling: str
    owner: str
    warn_after: str
    fail_after: str
    why: str


class RawErpMapping(BaseModel):
    model_config = ConfigDict(extra="forbid")

    ruling: str
    owner: str
    status: str
    map: dict[str, str]
    why: str
    cannot_be_stored_by_erp: list[str] = Field(default_factory=list)
    cannot_note: str = ""


class RawRelease(BaseModel):
    model_config = ConfigDict(extra="forbid")

    ruling: str
    creates_lot_at_status: str
    may_set_released: bool
    why: str


class RawNotDecided(BaseModel):
    model_config = ConfigDict(extra="forbid")

    what: str
    why: str
    owner: str


class RawPolicy(BaseModel):
    """The provisional rulings. Hand-authored and reviewed — see docs/working-answers.md."""

    model_config = ConfigDict(extra="forbid")

    policy_version: str = Field(min_length=1)
    status: str = Field(min_length=1)
    note: str = Field(min_length=1)
    spec_staleness: RawStaleness
    unit_conversions: list[RawUnitConversion]
    attribute_synonyms: RawSynonyms
    supplier_date_conventions: RawDateConventions
    rules: list[RawRule] = Field(min_length=1)
    erp_mapping: RawErpMapping
    release: RawRelease
    not_decided: list[RawNotDecided] = Field(default_factory=list)
